import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar chuyên mục An ninh mạng của IPZ Digital Solutions
 * Cấu hình tự động quét các file .md/.mdx trong thư mục tương ứng
 */
const sidebars: SidebarsConfig = {
  cyberSidebar: [
    {
      type: 'category',
      label: 'An ninh mạng',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '.', // Quét tự động toàn bộ thư mục docs/cybersecurity
        },
      ],
    },
  ],
};

export default sidebars;