import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  cyberSidebar: [{type: 'autogenerated', dirName: 'cyber'}],
  ipSidebar: [{type: 'autogenerated', dirName: 'ip'}],
  brandSidebar: [{type: 'autogenerated', dirName: 'brand'}],
  bioSidebar: [{type: 'autogenerated', dirName: 'bio'}],
};
export default sidebars;