import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Sidebar chuyên mục Tin sinh học của IPZ Digital Solutions
 * Cấu hình tự động quét các file .md/.mdx trong thư mục tương ứng
 */
const sidebars: SidebarsConfig = {
  ipSidebar: [
    {
      type: 'category',
      label: 'Bảo hộ Sở hữu trí tuệ',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: '.', // Quét tự động toàn bộ thư mục docs/bioinformatics
        },
      ],
    },
  ],
};

export default sidebars;